services:
  backend:
    image: ghcr.io/diagnoseteam/diagnose/backend:latest
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    volumes:
      # Volumen para la base de datos SQLite
      - db-data:/app/db
    restart: unless-stopped
    networks:
      - diagnose-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://diagnose.riberadeltajo.es/api
    image: ghcr.io/diagnoseteam/diagnose/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - diagnose-network

networks:
  diagnose-network:
    driver: bridge

volumes:
  db-data:
    driver: local
