services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - RUN_MIGRATIONS=true
    env_file:
      - ./backend/.env
    volumes:
      # Volumen para la base de datos SQLite
      - db-data:/app/db
    networks:
      - diagnose-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - diagnose-network

networks:
  diagnose-network:
    driver: bridge

volumes:
  db-data:
    driver: local
