"""Add keywords, referencias_bibliografica, codigo_cie_10 a casos clinicos

Revision ID: 83c9fc8ccf9f
Revises: b2a142210238
Create Date: 2026-05-05 09:05:09.781817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c9fc8ccf9f'
down_revision: Union[str, None] = 'b2a142210238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CasosClinicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referencias_bibliograficas', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('keywords', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('codigo_cie_10', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CasosClinicos', schema=None) as batch_op:
        batch_op.drop_column('codigo_cie_10')
        batch_op.drop_column('keywords')
        batch_op.drop_column('referencias_bibliograficas')

    # ### end Alembic commands ###
