"""AppSettings con MAYUSCULA

Revision ID: c5d345389d00
Revises: d719c57a4009
Create Date: 2026-05-05 00:00:46.209933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d345389d00'
down_revision: Union[str, None] = 'd719c57a4009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('AppSettings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AppSettings_id'), ['id'], unique=False)

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_app_settings_id')

    op.drop_table('app_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_enabled', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index('ix_app_settings_id', ['id'], unique=False)

    with op.batch_alter_table('AppSettings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AppSettings_id'))

    op.drop_table('AppSettings')
    # ### end Alembic commands ###
