"""Modificacion Settings

Revision ID: d25a7f23d3cc
Revises: 83c9fc8ccf9f
Create Date: 2026-05-06 12:44:09.103687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d25a7f23d3cc"
down_revision: Union[str, None] = "83c9fc8ccf9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("AppSettings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reviews_enabled", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("max_reviews_per_case", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("AppSettings", schema=None) as batch_op:
        batch_op.drop_column("allow_new_users")
        batch_op.drop_column("maintenance_mode")

    # ### end Alembic commands ###
