"""chat, historic and app_settings tables

Revision ID: d719c57a4009
Revises: f1eb22e21e6a
Create Date: 2026-05-04 23:55:52.629364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd719c57a4009'
down_revision: Union[str, None] = 'f1eb22e21e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_settings_id'), ['id'], unique=False)

    op.create_table('Chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('activo', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Historicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_chat', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=False),
    sa.Column('mensaje', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['id_chat'], ['Chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Historicos')
    op.drop_table('Chats')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_id'))

    op.drop_table('app_settings')
    # ### end Alembic commands ###
