"""First migration

Revision ID: f1eb22e21e6a
Revises: 
Create Date: 2026-05-03 20:56:53.065126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1eb22e21e6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CasosClinicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alergias', sa.String(length=255), nullable=True),
    sa.Column('antecedentes_familiares', sa.String(length=255), nullable=True),
    sa.Column('antecedentes_medicos', sa.String(length=255), nullable=True),
    sa.Column('antecedentes_quirurgicos', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('diagnostico_final', sa.String(length=255), nullable=True),
    sa.Column('dificultad', sa.String(length=100), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('exploracion_general', sa.String(length=255), nullable=True),
    sa.Column('factores_sociales', sa.String(length=255), nullable=True),
    sa.Column('habitos', sa.String(length=255), nullable=True),
    sa.Column('medicacion_actual', sa.String(length=255), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('razonamiento_clinico', sa.String(length=255), nullable=True),
    sa.Column('resultados_pruebas', sa.String(length=255), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('signos', sa.String(length=255), nullable=True),
    sa.Column('sintomas', sa.String(length=255), nullable=True),
    sa.Column('situacion_basal', sa.String(length=255), nullable=True),
    sa.Column('tratamiento_farmacologico', sa.String(length=255), nullable=True),
    sa.Column('tratamiento_no_farmacologico', sa.String(length=255), nullable=True),
    sa.Column('agente', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['Roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('Valoraciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_caso', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=255), nullable=True),
    sa.Column('precision_diagnostica', sa.Integer(), nullable=False),
    sa.Column('claridad_textual', sa.Integer(), nullable=False),
    sa.Column('relevancia_clinica', sa.Integer(), nullable=False),
    sa.Column('adecuacion_contextual', sa.Integer(), nullable=False),
    sa.Column('nivel_tecnico', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_caso'], ['CasosClinicos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Valoraciones')
    op.drop_table('Usuarios')
    op.drop_table('Roles')
    op.drop_table('CasosClinicos')
    # ### end Alembic commands ###
