"""app settings

Revision ID: fff7adbc66f2
Revises: f1eb22e21e6a
Create Date: 2026-05-04 23:19:09.957052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff7adbc66f2'
down_revision: Union[str, None] = 'f1eb22e21e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('AppSettings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_AppSettings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AppSettings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_AppSettings_id'))

    op.drop_table('AppSettings')
    # ### end Alembic commands ###
